### ISSUE TITLE
Pass --score=n to args

### ISSUE THREAD

**Issue by chriselion** [pre-commit/mirrors-pylint#12]
Because pre-commit makes multiple calls to pylint by default, you get multiple score outputs (if there's an error), e.g 

```
pylint...................................................................Failed
hookid: pylint

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)


--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

************* Module trainers.ppo.multi_gpu_policy
ml-agents/mlagents/trainers/ppo/multi_gpu_policy.py:31:8: W0201: Attribute 'devices' defined outside __init__ (attribute-defined-outside-init)
# <snip>

------------------------------------------------------------------
Your code has been rated at 9.89/10 (previous run: 9.89/10, +0.00)


--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
# same 8 more times.
```

Passing `args: [--score=n]` locally cleans this up to just 
```
pylint...................................................................Failed
hookid: pylint

************* Module trainers.ppo.multi_gpu_policy
ml-agents/mlagents/trainers/ppo/multi_gpu_policy.py:31:8: W0201: Attribute 'devices' defined outside __init__ (attribute-defined-outside-init)
```

I can make a PR, just not sure what the versioning process is.

**Comment by asottile** [comment]
The configuration for these comes from https://github.com/pre-commit/cron-mirror-creation

seems fine to me :+1: 

(then again, I usually turn of `pylint`'s score in pylintrc since I don't find negative reinforcement useful)

**Comment by chriselion** [comment]
> seems fine to me

You mean the current output seems OK, or the proposed change sounds OK?

Haven't dug through all the cron logic yet - do you mean it will get overwritten if I make a change?

**Comment by asottile** [comment]
the change seems fine

yeah if a change is made to `mirrors-pylint` it'll get overwritten -- pylint is configured [here](https://github.com/pre-commit/cron-mirror-creation/blob/6a931ca0bb518e4d9de93d53b071a8746da0111f/push.py#L38) in `cron-mirror-creation`

**Comment by chriselion** [comment]
https://github.com/pre-commit/cron-mirror-creation/pull/13
