### ISSUE TITLE
Automatic tag mirror broken due to Pylint tag format change

### ISSUE THREAD

**Issue by ulope** [pre-commit/mirrors-pylint#17]
Starting with `2.8.2` pylint has changed the tag format from `pylint-X.Y.Z` to `vX.Y.Z`.
See: http://pylint.pycqa.org/en/latest/whatsnew/2.9.html

This seems to break the automatic mirroring.

**Comment by asottile** [comment]
we don't look at tags https://github.com/pre-commit/mirrors-pylint/releases

versions never go backwards in this repository so older versions won't be picked up after 3.0.0a0

**Comment by ulope** [comment]
Hm I'm not sure I understand the rationale. 

IIUC this means for example that also backported fix releases will never get picked up. 
This seems problematic for tools that change behaviour between versions 

And also as it happens in this case where a major release alpha version blocks any further stable releases.

**Comment by asottile** [comment]
because it's simpler
