### ISSUE TITLE
Invalid distribution name or version syntax

### ISSUE THREAD

**Issue by cknv** [pre-commit/mirrors-pylint#5]
When installing in a fresh env I am getting the following error:

`error: Invalid distribution name or version syntax: -dummy-package-0.0.0`

I believe that the package name needs to be changed, much like it was done on the [pep257 checker](https://github.com/FalconSocial/pre-commit-mirrors-pep257/pull/4).

**Comment by asottile** [comment]
Ah thanks, I'll update the mirror maker and then all the ones under the org.

A workaround is to use an older version of virtualenv (13?)

**Comment by asottile** [comment]
closed via https://github.com/pre-commit/mirrors-pylint/commit/36741aba5056932b6d9b7be435c28cecb80c59bf

Thanks for the report!
